### ISSUE TITLE
new NatureServe API version: v1.1

### ISSUE THREAD

**Issue by sckott** [ropensci/natserv#21]
new api doc site https://explorer.natureserve.org/api-docs/#_overview_of_search_services

the old api docs site is gone, redirects to the new one. 

looks like the api is quite different, will probably need to rework pkg api, etc. probably bump to major version, v1

pushing v0.4 now, work on this later

**Comment by dhauverNS** [comment]
Hi, Dave Hauver from NatureServe here.

I wanted to provide some context for this change. On March 12, we relaunched our[ NatureServe Explorer website](https://explorer.natureserve.org), which is where we publish the information about the more than 100,000 rare and endangered species that NatureServe tracks through the Americas.

This relaunch is more than a cosmetic update; we have made fundamental changes that significantly expand the number of taxa published to the site, the information published for each, and the frequency with which subsequent updates are published. Whereas the old Explorer's data set was occasionally refreshed approximately once a year, we are now incrementally publishing updated data as it becomes available.

The new site includes a REST web services API that returns JSON data. As you already noted, you can find the documentation at https://explorer.natureserve.org/api-docs/

The new web services replace the XML-based web services that provided access to the original Explorer's data. The older services, known as our Internet Data Delivery (IDD) web services, will remain operational at https://services.natureserve.org/idd/ until June 15, 2020 in order to allow you to transition to the new API. If you need to access the documentation for the older web services, it's probably easiest to look at the most recent Internet Archive snapshot at https://web.archive.org/web/20191014140936/http://services.natureserve.org/

It is important to note that the underlying data returned by the XML-based web services is now out-of-date. Its data set was not refreshed when the new Explorer site launched. We encourage you to transition to our new API as soon as possible to ensure you are using the most current version of NatureServe's data.

If you have any questions, please don’t hesitate to either reach out to me or to contact us through https://explorer.natureserve.org/ContactUs

Thanks!

**Comment by sckott** [comment]
thanks @dhauverNS for these details - i've been meaning to get to this, hopefully this week
